### PR TITLE
Prevent errors when running with a non-0.0.0.0 address binding.

### LINKED ISSUE #10893: Crashes on startup when not listening on 0.0.0.0
## Observed behavior

If I run Kolibri 0.16.0a15 with `KOLIBRI_LISTEN_ADDRESS=127.0.0.1`, it crashes on startup:

```
wjt@toolbox:~☭ KOLIBRI_LISTEN_ADDRESS=127.0.0.1 ./tmp/kolibri/bin/kolibri start
[…]
INFO     2023-06-22 11:11:42,874 Starting Kolibri 0.16.0a15
Traceback (most recent call last):
  File "/sysroot/home/wjt/./tmp/kolibri/bin/kolibri", line 8, in <module>
    sys.exit(main())
  File "/sysroot/home/wjt/tmp/kolibri/lib/python3.9/site-packages/kolibri/dist/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/sysroot/home/wjt/tmp/kolibri/lib/python3.9/site-packages/kolibri/dist/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/sysroot/home/wjt/tmp/kolibri/lib/python3.9/site-packages/kolibri/dist/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/sysroot/home/wjt/tmp/kolibri/lib/python3.9/site-packages/kolibri/utils/cli.py", line 200, in invoke
    return super(KolibriDjangoCommand, self).invoke(ctx)
  File "/sysroot/home/wjt/tmp/kolibri/lib/python3.9/site-packages/kolibri/dist/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/sysroot/home/wjt/tmp/kolibri/lib/python3.9/site-packages/kolibri/dist/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/sysroot/home/wjt/tmp/kolibri/lib/python3.9/site-packages/kolibri/utils/cli.py", line 259, in start
    server.start(
  File "/sysroot/home/wjt/tmp/kolibri/lib/python3.9/site-packages/kolibri/utils/server.py", line 740, in start
    bus = KolibriProcessBus(
  File "/sysroot/home/wjt/tmp/kolibri/lib/python3.9/site-packages/kolibri/utils/server.py", line 713, in __init__
    super(KolibriProcessBus, self).__init__(*args, **kwargs)
  File "/sysroot/home/wjt/tmp/kolibri/lib/python3.9/site-packages/kolibri/utils/server.py", line 688, in __init__
    zeroconf_plugin = ZeroConfPlugin(self, self.port)
  File "/sysroot/home/wjt/tmp/kolibri/lib/python3.9/site-packages/kolibri/utils/server.py", line 281, in __init__
    self.bus.subscribe("SERVING", self.SERVING)
AttributeError: 'NoneType' object has no attribute 'subscribe'
```

I cannot reproduce this issue with 0.15.12. I believe this to be caused by d2dc7af0f05. Here is the offending function:

```python
class ZeroConfPlugin(Monitor):
    def __init__(self, bus, port):
        self.port = port
        if conf.OPTIONS["Deployment"]["LISTEN_ADDRESS"] == "0.0.0.0":
            # Only bother doing dynamic updates of the zeroconf service if we're bound
            # to all available IP addresses.
            Monitor.__init__(self, bus, self.run, frequency=5)
        self.bus.subscribe("SERVING", self.SERVING)
        self.bus.subscribe("UPDATE_ZEROCONF", self.UPDATE_ZEROCONF)
        self.broadcast = None
```

Notice that, in the case where `LISTEN_ADDRESS` is not `0.0.0.0`, the superclass `__init__` is not called. (In my limited experience it is unusual for an `__init__` implementation to not chain up.) Here is an excerpt of `Monitor`'s parent class:

```python
class SimplePlugin(object):
    """Plugin base class which auto-subscribes methods for known channels."""

    bus = None
    """A :class:`Bus <magicbus.Bus>`."""

    def __init__(self, bus):
        self.bus = bus
```

So without calling `__init__`, `self.bus` will be `None`. In other words, if `LISTEN_ADDRESS` is anything other than `0.0.0.0` then this function is guaranteed to crash.

Of course there is no need to do ZeroConf if listening only on localhost, but the same bug occurs if you have a device with multiple real network interfaces and want Kolibri to only listen on one of them, e.g. with `KOLIBRI_LISTEN_ADDRESS=192.168.0.19`.

## Errors and logs

(As above.)

## Expected behavior

* Kolibri should start, listening only on the given address.

## User-facing consequences

My actual goal here is to avoid a Windows firewall warning when Kolibri is first launched. I believe (without proof) that this warning is being shown because Kolibri is trying to listen on a non-localhost interface.

## Steps to reproduce

- Configure Kolibri to listen on an address other than `0.0.0.0`
- Launch Kolibri

## Context

- Kolibri version: 0.16.0a15
- OS: Endless OS (Linux), Windows

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary
* Still run the __init__ method for the parent class of the ZeroConfPlugin but do it in a way that prevents the polling behaviour

## References
Fixes [#10893](https://github.com/learningequality/kolibri/issues/10893)

## Reviewer guidance
Run `KOLIBRI_LISTEN_ADDRESS=127.0.0.1 kolibri start --foreground` and ensure that it does not error during startup

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [x] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Review by jredrejo — APPROVED** [review]
LGTM
