### PR TITLE
Fix exam conversion and difficult question bugs

### LINKED ISSUE #5623: Error in difficult questions tab after I upgrade the Kolibri 0.10.3 to 0.12.4 beta 6
### Observed behavior

When I click the question link in the difficult question tab there was error message appeared `Sorry Something went wrong!`. When I click the `Help us by reporting the error` there was no `Error details`  shown.

When I open the console on my browser I got an error message that `exam.question_sources.find(...) is undefined`, `this.text.split is not a function` and `this.$refs.copyButton is undefined`.

error_in_difficultQuestions

### Expected behavior

Can see the difficult question page.

### User-facing consequences

If there are errors occur, It must display in error details.

### Errors and logs

```
[ERROR: kolibri/plugins/coach/assets/src/modules/pluginModule.js] TypeError: "exam.question_sources.find(...) is undefined"
    promise handlers.js:49
    run draggable.bundle.legacy.js:12257
    notify draggable.bundle.legacy.js:12274
    flush draggable.bundle.legacy.js:11999
pluginModule.js:67:14
    handleCoachPageError pluginModule.js:67
    installModule vuex.esm.js:721
    dispatch vuex.esm.js:428
    dispatch vuex.esm.js:322
    showQuestionDetailView handlers.js:106
    run draggable.bundle.legacy.js:12257
    notify draggable.bundle.legacy.js:12274
    flush draggable.bundle.legacy.js:11999

TypeError: "this.text.split is not a function"
    dynamicHeightStyle TechnicalTextBlock.vue:66
    VueJS 3
        get
        evaluate
        createComputedGetter
    component TechnicalTextBlock.vue:1
    VueJS 57
        _render
        updateComponent
        get
        Watcher
        mount
        $mount
        init
        createElm
        createElm
        createChildren
        createElm
        createChildren
        createElm
        createChildren
        createElm
        createChildren
        createElm
        patch
        _update
        updateComponent
        get
        Watcher
        mount
        $mount
        init
        createElm
        createElm
        patch
        _update
        updateComponent
        get
        Watcher
        mount
        $mount
        init
        createElm
        createElm
        patch
        _update
        updateComponent
        get
        Watcher
        mount
        $mount
        init
        createElm
        createElm
        patchVnode
        patchVnode
        patch
        _update
        updateComponent
        get
        run
        flushSchedulerQueue
        nextTick
        flushCallbacks
    run es6.promise.js:75
    notify es6.promise.js:92
    flush _microtask.js:18
vue.runtime.esm.js:1887

TypeError: "this.$refs.copyButton is undefined"
    mounted TechnicalTextBlock.vue:74
    VueJS 12
        invokeWithErrorHandling
        callHook
        insert
        invokeInsertHook
        patch
        _update
        updateComponent
        get
        run
        flushSchedulerQueue
        nextTick
        flushCallbacks
    run es6.promise.js:75
    notify es6.promise.js:92
    flush _microtask.js:18
vue.runtime.esm.js:1887
```

…

### Steps to reproduce

1. Install the Kolibri [0.10.3](http://pantry.learningequality.org/downloads/kolibri/v0.10.3/kolibri-v0.10.3-windows-setup.exe)
2. Create a quiz interaction using this [gherkin scenario](https://github.com/learningequality/kolibri/blob/v0.12.4-beta6/integration_testing/features/coach/coach-lesson-difficult-questions.feature)
3. Then Upgrade to [Kolibri 0.12.4 beta 6](https://github.com/learningequality/kolibri/releases/download/v0.12.4-beta6/kolibri-0.12.4b6-unsigned.exe)
4. Then clicks the question link in the `Difficult question tab` and see the error message in the console.
### Context

Tell us about your environment, including:
 * Kolibri version: 0.10.3 to 0.12.4b6
 * Operating system: Windows 10
 * Browser: Firefox 67.0 (32-bit)

…

### LINKED ISSUE #5626: Unattempted answers in a quiz should not show up as difficult questions?
### Observed behavior
Unattempted answers in a quiz show up as _difficult questions_  immediately upon learner opening the quiz.

unattempted-diffque

In the above example all 5 questions are categorized as difficult even though the second learner has just started the quiz, and haven't even viewed the questions 2-5.

### Expected behavior
Label questions as difficult _only_ after the quiz has been submitted? Or more complex one would be to have the `viewed and skipped more than once` as the threshold for unattempted question labeled as difficult?

### User-facing consequences
Coaches getting overestimates about the number of difficult questions. 

### Errors and logs

…

### Steps to reproduce

…

### Context

 * Kolibri version: 0.12.4b6 upgraded from 0.10
 * Operating system: Ubuntu 16.04
 * Browser: all

cc @rtibbles @indirectlylit (I did not put the milestone, in case the fix is out of the scope for now)

### PR DESCRIPTION
**Pull request by jonboiser**
### Summary

1. Adds `seed` to the `ExamSerializer` used in the `ClassSummary` API, fixes #5623, by making sure `data_model_version = 0` quizzes are converted properly on the Difficult Questions tab.
1. Converts `data_model_version = 0` quizzes at the Plan > QuizSummaryPage, which fixes the quiz previewer.
1. Fixes implementation of `handleCoachError`, so that the AppError page shows the details properly.
1. Changes the response of the `QuizDifficultQuestionsViewset` to only return logs of submitted quizzes when quiz is active, or when quiz is closed. It does not returns logs of not-submitted quizzes wile the quiz is still active (fixes #5626)
1. Some refactors

### Reviewer guidance

1. To test that #5623 has been fixed, create an quiz in Kolibri v0.11 or older, to make sure that it is using `data_model_version = 0`. Then upgrade to the version in this code. The quiz functionality should work (learners can take quiz, coaches can view reports, preview it, edit, copy it etc.)
1. To test that #5626 has been fixed, create a quiz, activate it, and take it as a single learner. You can skip or get problems wrong and on the coach "Difficult Questions" tab for the quiz, no questions should appear until you submit the quiz or close it.

### References

…

----

### Contributor Checklist

PR process:

- [x] PR has the correct target branch and milestone
- [x] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

Testing:

- [ ] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

### Reviewer Checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by rtibbles** [comment]
Code looks ok to me - not sure I have all the relevant data locally to confirm fixes. @radinamatic would you be able to follow up on the functional testing?

**Comment by radinamatic** [comment]
Yep, will test asap @rtibbles! :+1:

**Comment by radinamatic** [comment]
- [X] #5623: I upgraded from version 0.10.3, where the facility already had one exam submitted by one learner. After the upgrade I was able to take the same exam/quiz as another learner, engage the copy of the exam in another class as a third learner, and the class activity, reports, quiz preview are viewable by the coach without problems! 👍 

- [X] #5626: nothing appears under "Difficult Questions" tab for a quiz until it is submitted, **just closing the  quiz, without submitting does not label incorrectly answered quiz questions as _Difficult_** (from @jonboiser's comment I'm not sure if that was also the goal).

**Comment by rtibbles** [comment]
> just closing the quiz, without submitting does not label incorrectly answered quiz questions as Difficult

Do you mean a student closing the quiz, or a teacher deactivating the quiz?

(The former should not flag a question as difficult, the latter should).

**Comment by radinamatic** [comment]
At the end of @jonboiser *Reviewer guidance* there was:
> no questions should appear until you submit the quiz **or close it.**

I interpreted it as a **learner** closing the quiz, presumably to return to it later, but now I see what you mean: when coach deactivates the quiz, all the incorrect answers by a learner in a quiz they *did not submit*, do get labeled as difficult questions! :+1:

**Review by rtibbles — APPROVED** [review]
Code looks good, and behaviour fixes are confirmed by @radinamatic.
