### ISSUE TITLE
Error in difficult questions tab after I upgrade the Kolibri 0.10.3 to 0.12.4 beta 6

### ISSUE THREAD

**Issue by mrpau-julius** [learningequality/kolibri#5623]
### Observed behavior

When I click the question link in the difficult question tab there was error message appeared `Sorry Something went wrong!`. When I click the `Help us by reporting the error` there was no `Error details`  shown.

When I open the console on my browser I got an error message that `exam.question_sources.find(...) is undefined`, `this.text.split is not a function` and `this.$refs.copyButton is undefined`.

![error_in_difficultQuestions](https://user-images.githubusercontent.com/38421180/58929913-d5e0e380-878b-11e9-938f-f731195de5ae.png)

### Expected behavior

Can see the difficult question page.

### User-facing consequences

If there are errors occur, It must display in error details.

### Errors and logs

```
[ERROR: kolibri/plugins/coach/assets/src/modules/pluginModule.js] TypeError: "exam.question_sources.find(...) is undefined"
    promise handlers.js:49
    run draggable.bundle.legacy.js:12257
    notify draggable.bundle.legacy.js:12274
    flush draggable.bundle.legacy.js:11999
pluginModule.js:67:14
    handleCoachPageError pluginModule.js:67
    installModule vuex.esm.js:721
    dispatch vuex.esm.js:428
    dispatch vuex.esm.js:322
    showQuestionDetailView handlers.js:106
    run draggable.bundle.legacy.js:12257
    notify draggable.bundle.legacy.js:12274
    flush draggable.bundle.legacy.js:11999

TypeError: "this.text.split is not a function"
    dynamicHeightStyle TechnicalTextBlock.vue:66
    VueJS 3
        get
        evaluate
        createComputedGetter
    component TechnicalTextBlock.vue:1
    VueJS 57
        _render
        updateComponent
        get
        Watcher
        mount
        $mount
        init
        createElm
        createElm
        createChildren
        createElm
        createChildren
        createElm
        createChildren
        createElm
        createChildren
        createElm
        patch
        _update
        updateComponent
        get
        Watcher
        mount
        $mount
        init
        createElm
        createElm
        patch
        _update
        updateComponent
        get
        Watcher
        mount
        $mount
        init
        createElm
        createElm
        patch
        _update
        updateComponent
        get
        Watcher
        mount
        $mount
        init
        createElm
        createElm
        patchVnode
        patchVnode
        patch
        _update
        updateComponent
        get
        run
        flushSchedulerQueue
        nextTick
        flushCallbacks
    run es6.promise.js:75
    notify es6.promise.js:92
    flush _microtask.js:18
vue.runtime.esm.js:1887

TypeError: "this.$refs.copyButton is undefined"
    mounted TechnicalTextBlock.vue:74
    VueJS 12
        invokeWithErrorHandling
        callHook
        insert
        invokeInsertHook
        patch
        _update
        updateComponent
        get
        run
        flushSchedulerQueue
        nextTick
        flushCallbacks
    run es6.promise.js:75
    notify es6.promise.js:92
    flush _microtask.js:18
vue.runtime.esm.js:1887
```

…

### Steps to reproduce

1. Install the Kolibri [0.10.3](http://pantry.learningequality.org/downloads/kolibri/v0.10.3/kolibri-v0.10.3-windows-setup.exe)
2. Create a quiz interaction using this [gherkin scenario](https://github.com/learningequality/kolibri/blob/v0.12.4-beta6/integration_testing/features/coach/coach-lesson-difficult-questions.feature)
3. Then Upgrade to [Kolibri 0.12.4 beta 6](https://github.com/learningequality/kolibri/releases/download/v0.12.4-beta6/kolibri-0.12.4b6-unsigned.exe)
4. Then clicks the question link in the `Difficult question tab` and see the error message in the console.
### Context

Tell us about your environment, including:
 * Kolibri version: 0.10.3 to 0.12.4b6
 * Operating system: Windows 10
 * Browser: Firefox 67.0 (32-bit)

…

**Comment by radinamatic** [comment]
Managed to replicate this on the same upgrade scenario but on Ubuntu 16.04:

![quiz-diffque](https://user-images.githubusercontent.com/1457929/59052852-57ba3500-8890-11e9-8140-815e45a809b1.gif)


![Ub1604-0 12 4b6  Running  - Oracle VM VirtualBox_075](https://user-images.githubusercontent.com/1457929/59051818-07da6e80-888e-11e9-8d87-4892a5975bad.png)

The quiz in question was created as `exam` on 0.10, that is prior to the upgrade to 0.12.4b6. When I try to preview the quiz in 0.12.4 it displays as containing only one question:

![Ub1604-0 12 4b6  Running  - Oracle VM VirtualBox_076](https://user-images.githubusercontent.com/1457929/59052252-f5146980-888e-11e9-973c-1c7ca6183089.png)

But if reviewed as the report for the learner I can see all 5 questions... :thinking: 

![Ub1604-0 12 4b6  Running  - Oracle VM VirtualBox_078](https://user-images.githubusercontent.com/1457929/59052950-8e904b00-8890-11e9-9da4-a87faef132a8.png)

Log file here, although I can't see anything remarkable: [kolibri.txt](https://github.com/learningequality/kolibri/files/3262719/kolibri.txt)

[Full DB from the device](https://drive.google.com/open?id=1a8imj_orCoD7P1ygm_6hWc6Il5dmnY5c) the first time error occurred (6MB) 

There seem to be two issues here:
- inability to review the difficult question (`Something went wrong...` error
- error report not being created

@indirectlylit Could we maybe work on the second issue for the 0.12.4?

**Comment by jonboiser** [comment]
Looked into this quickly, and when I do this, the `question_id` UUIDs used in the Difficult Question links don't match any of the IDs recorded in the old exam's (data model V0) `question_sources`, which causes this `.find` to return undefined, and the problems.

https://github.com/learningequality/kolibri/blob/9eac2944934d24e4a631d1a8c673047662965b66/kolibri/plugins/coach/assets/src/modules/questionDetail/handlers.js#L49

**Comment by jonboiser** [comment]
This issue might be related to #5626, as I think the problem in that issue and his one might be that the incorrect data is being set in the `SET_ITEMSTATS` mutation:

https://github.com/learningequality/kolibri/blob/554b27f3c457504dc86398543b8bdbafcc5af11c/kolibri/plugins/coach/assets/src/modules/questionList/actions.js#L45-L83

Which may be related to the error one gets when going to the difficult questions pages:

```
ERROR: kolibri/core/assets/src/api-resource.js] detail detail endpoint does not exist on kolibri:coach:quizdifficulties.```

**Comment by jonboiser** [comment]
And the reason for this mismatch seems to be that the `classSummary.quizMap` `quiz` objects are missing a `seed` field, so the converter must be shuffling the exercises differently between the two pages.

**Comment by rtibbles** [comment]
Fixed in #5674
