### ISSUE TITLE
Find a solution for bundled cryptography pkg that works for Ubuntu 14.04 (Trusty)

### ISSUE THREAD

**Issue by lyw07** [learningequality/kolibri#2544]
### Observed behavior

I'm not able to import channel from browser or command line. When importing from browser, it shows that transfer failed.

### Expected behavior

Importing channels successfully.

### User-facing consequences

Users will not able to import a channel when their Python version is not the latest (or probably some other reasons that cause this problem).

### Errors and logs

Relevant errors and tracebacks from:

* the command line
```
WARNING:py.warnings:/home/osboxes/.pex/install/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl.f6b31bfd2a0b1e7de7753e26a8255f5d5f146d78/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl/kolibri/dist/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning

WARNING:py.warnings:/home/osboxes/.pex/install/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl.f6b31bfd2a0b1e7de7753e26a8255f5d5f146d78/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl/kolibri/dist/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

Traceback (most recent call last):
  File "/home/osboxes/share/kolibri-0.7.dev020171030053720-git.pex/.bootstrap/_pex/pex.py", line 365, in execute
  File "/home/osboxes/share/kolibri-0.7.dev020171030053720-git.pex/.bootstrap/_pex/pex.py", line 293, in _wrap_coverage
  File "/home/osboxes/share/kolibri-0.7.dev020171030053720-git.pex/.bootstrap/_pex/pex.py", line 325, in _wrap_profiling
  File "/home/osboxes/share/kolibri-0.7.dev020171030053720-git.pex/.bootstrap/_pex/pex.py", line 408, in _execute
  File "/home/osboxes/share/kolibri-0.7.dev020171030053720-git.pex/.bootstrap/_pex/pex.py", line 466, in execute_entry
  File "/home/osboxes/share/kolibri-0.7.dev020171030053720-git.pex/.bootstrap/_pex/pex.py", line 471, in execute_module
  File "/usr/lib/python2.7/runpy.py", line 180, in run_module
    fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/osboxes/.pex/install/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl.f6b31bfd2a0b1e7de7753e26a8255f5d5f146d78/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl/kolibri/__main__.py", line 8, in <module>
    main(args=sys.argv[1:])
  File "/home/osboxes/.pex/install/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl.f6b31bfd2a0b1e7de7753e26a8255f5d5f146d78/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl/kolibri/utils/cli.py", line 629, in main
    manage(command, args=django_args)
  File "/home/osboxes/.pex/install/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl.f6b31bfd2a0b1e7de7753e26a8255f5d5f146d78/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl/kolibri/utils/cli.py", line 460, in manage
    execute_from_command_line(argv=argv)
  File "/home/osboxes/.pex/install/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl.f6b31bfd2a0b1e7de7753e26a8255f5d5f146d78/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl/kolibri/dist/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/osboxes/.pex/install/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl.f6b31bfd2a0b1e7de7753e26a8255f5d5f146d78/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl/kolibri/dist/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/osboxes/.pex/install/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl.f6b31bfd2a0b1e7de7753e26a8255f5d5f146d78/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl/kolibri/dist/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/osboxes/.pex/install/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl.f6b31bfd2a0b1e7de7753e26a8255f5d5f146d78/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl/kolibri/dist/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/osboxes/.pex/install/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl.f6b31bfd2a0b1e7de7753e26a8255f5d5f146d78/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl/kolibri/tasks/management/commands/base.py", line 99, in handle
    return self.handle_async(*args, **options)
  File "/home/osboxes/.pex/install/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl.f6b31bfd2a0b1e7de7753e26a8255f5d5f146d78/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl/kolibri/content/management/commands/importchannel.py", line 89, in handle_async
    self.download_channel(options["channel_id"])
  File "/home/osboxes/.pex/install/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl.f6b31bfd2a0b1e7de7753e26a8255f5d5f146d78/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl/kolibri/content/management/commands/importchannel.py", line 42, in download_channel
    self._transfer(DOWNLOAD_METHOD, channel_id)
  File "/home/osboxes/.pex/install/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl.f6b31bfd2a0b1e7de7753e26a8255f5d5f146d78/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl/kolibri/content/management/commands/importchannel.py", line 67, in _transfer
    with filetransfer:
  File "/home/osboxes/.pex/install/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl.f6b31bfd2a0b1e7de7753e26a8255f5d5f146d78/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl/kolibri/content/utils/transfer.py", line 98, in __enter__
    self.start()
  File "/home/osboxes/.pex/install/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl.f6b31bfd2a0b1e7de7753e26a8255f5d5f146d78/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl/kolibri/content/utils/transfer.py", line 153, in start
    self.source, stream=True, timeout=self.timeout)
  File "/home/osboxes/.pex/install/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl.f6b31bfd2a0b1e7de7753e26a8255f5d5f146d78/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl/kolibri/dist/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/home/osboxes/.pex/install/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl.f6b31bfd2a0b1e7de7753e26a8255f5d5f146d78/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl/kolibri/dist/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/osboxes/.pex/install/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl.f6b31bfd2a0b1e7de7753e26a8255f5d5f146d78/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl/kolibri/dist/requests/sessions.py", line 606, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/home/osboxes/.pex/install/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl.f6b31bfd2a0b1e7de7753e26a8255f5d5f146d78/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl/kolibri/dist/requests/sessions.py", line 179, in resolve_redirects
    **adapter_kwargs
  File "/home/osboxes/.pex/install/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl.f6b31bfd2a0b1e7de7753e26a8255f5d5f146d78/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl/kolibri/dist/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/home/osboxes/.pex/install/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl.f6b31bfd2a0b1e7de7753e26a8255f5d5f146d78/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl/kolibri/dist/requests/adapters.py", line 477, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
```
* `~/.kolibri/kolibri.log`

No errors shown here.

* the browser console

   Same as above

```
server logs
```

```
 WARNING:py.warnings:/home/osboxes/.pex/install/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl.f6b31bfd2a0b1e7de7753e26a8255f5d5f146d78/kolibri-0.7.dev020171030053720_git-py2.py3-none-any.whl/kolibri/dist/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
```

### Steps to reproduce

1. Set up a Ubuntu 14.04 32-bit VM with python 2.7.6 installed (this python version comes with the VM)
2. Use the latest 0.7 pex to start the server
3. From command line or browser, try to import a channel

### Context

* Kolibri version: 0.7
* Operating system: Ubuntu 14.04
* Browser: Firefox

**Comment by lyw07** [comment]
Tried with delete the `requests` module in the `.pex` folder and install with `requests[security]`, but it's not working.

**Comment by benjaoming** [comment]
@lyw07 could you try running `./file.pex shell` and then:

```
>>> import requests
>>> print(requests.__file__)
```

Also, are you building this Pex with Python 2 or 3? A known issue is that you cannot build with Python 3 and run with Python 2.

**Comment by lyw07** [comment]
@benjaoming  Here is the result:

> /home/osboxes/.pex/install/kolibri-0.7.dev020171031202733_git-py2.py3-none-any.whl.5bac861fe6e0a0532471a7651fb08201bd7608e8/kolibri-0.7.dev020171031202733_git-py2.py3-none-any.whl/kolibri/dist/requests/__init__.py

The pex file I'm running is the latest pex from develop branch. I think on buildkite, when we create the pex from docker, we use Python 2? 

I checked with the latest pex file from release-0.6.x branch on the same Ubuntu machine, and the error doesn't exist.

**Comment by lyw07** [comment]
@aronasorman the error still exists with the latest 0.7 pex file.

**Comment by aronasorman** [comment]
Fixed in #2651

**Comment by benjaoming** [comment]
> requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

Is this error because we hardened a web server's config so much that it doesn't support SSLv3 but only TLS?

**Comment by benjaoming** [comment]
Well, at least our server is very well configured :)

![image](https://user-images.githubusercontent.com/374612/33893250-45b0b7a6-df5b-11e7-8f66-2d0c13b33877.png)

**Comment by benjaoming** [comment]
For whatever reason, the client is failing an SSLv3 handshake, and this protocol isn't supported by either us or CloudFlare (not sure which part dictates the certificates and the configurations)

![image](https://user-images.githubusercontent.com/374612/33893355-812fd7d0-df5b-11e7-88c9-fc2923345fe1.png)

**Comment by benjaoming** [comment]
This seems to be another issue regarding cryptography and OpenSSL libraries that we bundle vs. the ones on the system.

See also: `https://github.com/requests/requests/issues/2778`

**Comment by lyw07** [comment]
Thank you for the link! It's very helpful. I will set up a Trusty VM to look into this issue more

**Comment by lyw07** [comment]
It seems that the issue was because `studio.learningequality.org` requires SNI.
<img width="514" alt="screen shot 2017-12-13 at 4 59 32 pm" src="https://user-images.githubusercontent.com/19424916/33970274-08510146-e027-11e7-8428-3d3c08e871c9.png">

The Ubuntu 14.04 VM comes with Python 2.7.6 which doesn't support SNI. Indeed, SNI was not supported by python until 2.7.9 according to the table [here](https://en.wikipedia.org/wiki/Server_Name_Indication).

I tried with upgrading Python to 2.7.9, and the error went away. I'm not sure if it was something else in Python 2.7.9 that fixed the error though..

There's also a way to deal with it regarding `requests`, here's a stack overflow [answer](https://stackoverflow.com/questions/18578439/using-requests-with-tls-doesnt-give-sni-support/18579484#18579484). But I haven't tried it yet. It also indicates that we will need to bundle more things into Kolibri to make it work, which doesn't seem to be a nice way for us to do.

Anyways, I will dig into this more tomorrow to see if there are other ways to deal with the issue.

Here are the two commands with and without servername option added:

```
lingyiwang$ openssl s_client -connect studio.learningequality.org:443
CONNECTED(00000003)
12721:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-59.60.1/src/ssl/s23_clnt.c:593:
```

```
lingyiwang$ openssl s_client -connect studio.learningequality.org:443 -servername studio.learningequality.org
CONNECTED(00000003)
depth=1 /C=US/ST=CA/L=San Francisco/O=CloudFlare, Inc./CN=CloudFlare Inc RSA CA-1
verify error:num=20:unable to get local issuer certificate
verify return:0
---
Certificate chain
 0 s:/C=US/ST=CA/L=San Francisco/O=CloudFlare, Inc./CN=learningequality.org
   i:/C=US/ST=CA/L=San Francisco/O=CloudFlare, Inc./CN=CloudFlare Inc RSA CA-1
 1 s:/C=US/ST=CA/L=San Francisco/O=CloudFlare, Inc./CN=CloudFlare Inc RSA CA-1
   i:/C=IE/O=Baltimore/OU=CyberTrust/CN=Baltimore CyberTrust Root
---
Server certificate
-----BEGIN CERTIFICATE-----
(certificate)
-----END CERTIFICATE-----
subject=/C=US/ST=CA/L=San Francisco/O=CloudFlare, Inc./CN=learningequality.org
issuer=/C=US/ST=CA/L=San Francisco/O=CloudFlare, Inc./CN=CloudFlare Inc RSA CA-1
---
No client certificate CA names sent
---
SSL handshake has read 2891 bytes and written 462 bytes
---
New, TLSv1/SSLv3, Cipher is AES128-SHA
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1
    Cipher    : AES128-SHA

    Start Time: 1513214032
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
```
> Note: I deleted some of the result from the second command so that it won't be super long

**Comment by benjaoming** [comment]
@indirectlylit as @lyw07 pointed out...
> The Ubuntu 14.04 VM comes with Python 2.7.6

...the good ol' Trusty is supported until 2019. I know that Travis is still running it.

We can aim for an architecture that's Optimal For Most and doesn't Break For The Minority @indirectlylit -- I refer to the architecture, but also a bit on the decisions, for instance do we impose a "known issue" or a permanent scope of "supported platforms".

If we decide to bundle compiled libraries and this design doesn't account for systems where these libraries don't work or collide with other system libraries, then we shut out some unknown minority of platforms from ever using Kolibri. It's very hard to work around flaws in an application that wasn't designed to co-exist with the causes of the flaws :)

Problems identified:

1. SNI (which could be a Cloudflare requirement) is missing on old platforms: We could add a dependency for the package `python3-openssl`, since it seems that if you install pyOpenSSL, it would work. @lyw07 could you try running the same commands after installing `python-openssl` ?

1. Making sure that Kolibri works without `cryptography`: Should we add an entry to the test matrix that doesn't have `cryptography` at all. Currently, this isn't the case for Morango nor Kolibri's test matrices.

1. Making sure that the bundled `cryptography` package doesn't collide with system packages: Add a version of our source dist that doesn't contain anything compiled and add `python3-cryptography` as a dependency (which is also the consequence of adding dep. `python3-openssl`). In the longer run, perhaps write a Debian package that compiles stuff for specific architectures.

**Comment by lyw07** [comment]
@benjaoming I just ran the VM again. The package`python-openssl` has already been in the VM, and it's the newest version.. Do you have any suggestions about other packages that I could try? Thank you!!

**Comment by indirectlylit** [comment]
> I refer to the architecture, but also a bit on the decisions, for instance do we impose a "known issue" or a permanent scope of "supported platforms"

If I'm understanding the question correctly... I think it's totally reasonable to require users of Ubuntu 14.04 to upgrade from Python 2.7.6 to 2.7.9, particularly since SNI support seems to be a security-related fix.

**Comment by lyw07** [comment]
The newest version of `python-openssl` in Trusty is 0.13, but `requests` seems to [ask for at least 0.14](https://github.com/requests/requests/blob/v2.18.4/setup.py#L95)? 

I tried with upgrading pyopenssl to 0.14 through pip. There are three problems I encountered:
1. I had to upgrade pip and setuptools first to install. Otherwise the installation would fail with `Invalid environment marker: python_version < '3'`

2. After upgrading pyopenssl to 0.14, I wasn't able to start the server anymore, as there was the error `AttributeError: 'module' object has no attribute 'SSL_ST_INIT'`. I assume this means the version `pyopenssl` is not compatible with the version of system `openssl`? I tried with newer versions too, and they had the same error.

**Comment by lyw07** [comment]
If we install `pyopenssl` 16.2.0, the error `AttributeError: 'module' object has no attribute 'SSL_ST_INIT'` will go away. I checked that the size of `pyopenssl` is about 388KB if we don't install the dependencies (we have them bundled inside Kolibri already because of `cryptography`). So is it possible to bundle the 16.2.0 `pyopenssl` module without dependencies into Kolibri? Or maybe this won't work well, since we don't want to keep extending the size of kolibri installers?

**Comment by indirectlylit** [comment]
Am I correct in assuming that this issue was addressed with the recent distribution work for 0.7.1?

**Comment by lyw07** [comment]
@indirectlylit I just tested 0.7.1-beta1 on Ubuntu 14.04. It shows that this problem still exists when running on Python 2. This is because the system Python 2 `OpenSSL` module's version is old. I also tested with Python 3 on the VM. In my VM, I don't have the system Python 3 `OpenSSL` module installed, so the problem doesn't exist. I think the fix for this issue is https://github.com/learningequality/kolibri/pull/2966, which is currently in the develop branch.

However, I just realize that removing the 64-bit linux cryptography makes the fix for this issue ineffective.
After removing the 64-bit cryptography: 
1. For Ubuntu 14.04, since `pyopenssl` [depends on `cryptography`](https://github.com/pyca/pyopenssl/blob/17.4.0/setup.py#L98) and `cryptography` is not installed in the system, then installing a higher version of `pyopenssl` will not fix the issue we have here when running in Python 2. If the users don't install the system Python 3 `OpenSSL`, then the issue won't show up. However, if they do, then the same issue will appear as it is in Python 2.
2. For Ubuntu 16.04+, we currently rely on the system module `cryptography 1.2.3`. However, the `pyopenssl` version `17.4.0` depends on `cryptography` > 1.9, so it will raise another error when we try to download content from Kolibri.

@benjaoming Do you have any suggestions on this new issue? Thank you!!

**Comment by indirectlylit** [comment]
ok thanks @lyw07 

bumping this to 0.8

**Comment by indirectlylit** [comment]
I don't have data, but my impression is that ubuntu 14 is not critical. More important would be e.g. Android

**Comment by benjaoming** [comment]
@lyw07 

Sorry in advance if I'm adding a new layer of information to an already very lengthy set of comments.

The Debian packages only use Python 3. Currently, they only suggest `python3-cryptography` (which doesn't exist on 14.04 anyways).

I also tested  `kolibri shell` with `requests.get("https://studio.learningequality.org")` and this works as well.

Me and @radinamatic have tested the latest 0.7.1-beta2 build in regards to setup and channel importing, and the issue doesn't show up.

I'm unable to reproduce the original issue on Ubuntu 14.04, so I would assume that we just have a minor problem left now, namely that 14.04+Python2 doesn't work?

**Comment by lyw07** [comment]
ah sorry @benjaoming I didn't explain my thoughts clearly. Our 0.7.1 should be working perfectly after your fix. The above comment was related to my concern on the 0.8 release. I think we will get errors on our 0.8 debian installers with this PR https://github.com/learningequality/kolibri/pull/2966 after we merge 0.7.x branch into the develop branch. 

If you can try:
1. install the current 0.7.1 installer on 16.04
2. `pip install pyOpenSSL==17.4.0 --no-deps`
3. then in `kolibri shell`, run `requests.get("https://studio.learningequality.org")`

I think this is basically what we will have if we merge 0.7.x branch into develop branch. I remember I tried it once early this week, and it was having an error.

But anyways, I don't think we need to worry about this for 0.7.1 since it's working perfectly right now 🎉

**Comment by indirectlylit** [comment]
I believe this has been addressed - is that correct?

**Comment by lyw07** [comment]
yes the issue has been resolved. We bundle both cryptography and pyOpenSSL into kolibri, so they won't have incompatible issues depending on the distribution.

**Comment by indirectlylit** [comment]
thank you!

**Comment by benjaoming** [comment]
Also we don't seem to support Trusty anymore really? I know that it isn't stated in the latest docs, it was intentionally removed after Trusty reached end of life 9 days ago.

Trusty is still the default VM on Travis CI, so in reality, we might keep supporting it for a bit :)
